In [8]:
# from https://iamtrask.github.io//2015/07/12/basic-python-network/
import numpy as np

class NeuralNetwork():
    def __init__(self):
        # Seed the random number generator, so it generates the same numbers
        # every time the program runs.
        np.random.seed(1)

        # We model a single neuron, with 3 input connections and 1 output connection.
        # We assign random weights to a 3 x 1 matrix, with values in the range -1 to 1
        # and mean 0.
        self.synaptic_weights = 2 * np.random.random((4, 1)) - 1

    # The Sigmoid function, which describes an S shaped curve.
    # We pass the weighted sum of the inputs through this function to
    # normalise them between 0 and 1.
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    # The derivative of the Sigmoid function.
    # This is the gradient of the Sigmoid curve.
    # It indicates how confident we are about the existing weight.
    def __sigmoid_derivative(self, x):
        return x * (1 - x)

    # We train the neural network through a process of trial and error.
    # Adjusting the synaptic weights each time.
    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iteration in iter(range(number_of_training_iterations)):
            # Pass the training set through our neural network (a single neuron).
            output = self.think(training_set_inputs)

            # Calculate the error (The difference between the desired output
            # and the predicted output).
            error = training_set_outputs - output

            # Multiply the error by the input and again by the gradient of the Sigmoid curve.
            # This means less confident weights are adjusted more.
            # This means inputs, which are zero, do not cause changes to the weights.
            adjustment = np.dot(training_set_inputs.T, error * self.__sigmoid_derivative(output))

            # Adjust the weights.
            self.synaptic_weights += adjustment
            if (iteration % 1000 == 0):
                print ("error after %s iterations: %s" % (iteration, str(numpy.mean(numpy.abs(error)))))

    # The neural network thinks.
    def think(self, inputs):
        # Pass inputs through our neural network (our single neuron).
        return self.__sigmoid(np.dot(inputs, self.synaptic_weights))


if __name__ == "__main__":

    #Intialise a single neuron neural network.
    neural_network = NeuralNetwork()

    print ("Random starting synaptic weights: ")
    print (neural_network.synaptic_weights)

    # The training set. We have 4 examples, each consisting of 3 input values
    # and 1 output value.
    training_set_inputs = np.array([[0, 0, 1, 0], [1, 1, 0, 1], [1, 0, 0, 1], [0, 1, 1, 0]])
    training_set_outputs = np.array([[0, 1, 1, 0]]).T

    # Train the neural network using a training set.
    # Do it 10,000 times and make small adjustments each time.
    neural_network.train(training_set_inputs, training_set_outputs, 20000)

    print ("New synaptic weights after training: ")
    print (neural_network.synaptic_weights)

    # Test the neural network with a new pattern
    test = [1, 0, 1, 1]
    print ("Considering new situation %s -> ?: " % test )
    print (neural_network.think(np.array(test)))


Random starting synaptic weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]
 [-0.39533485]]
error after 0 iterations: 0.449903018833
error after 1000 iterations: 0.013750440233
error after 2000 iterations: 0.00965974377145
error after 3000 iterations: 0.00786218913086
error after 4000 iterations: 0.00679524113652
error after 5000 iterations: 0.00606919069443
error after 6000 iterations: 0.00553435906148
error after 7000 iterations: 0.00511936227674
error after 8000 iterations: 0.00478528276951
error after 9000 iterations: 0.00450886340585
error after 10000 iterations: 0.00427523967482
error after 11000 iterations: 0.00407440954071
error after 12000 iterations: 0.00389936317766
error after 13000 iterations: 0.00374502274318
error after 14000 iterations: 0.00360760779755
error after 15000 iterations: 0.00348423814505
error after 16000 iterations: 0.00337267580097
error after 17000 iterations: 0.00327115193553
error after 18000 iterations: 0.00317824759008
error after 19000 iterations

In [6]:
# a look inside one iteration
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)
    
sweights = [[-0.16595599],[ 0.44064899],[-0.99977125]]
print ("input:")
print (training_set_inputs)
print ("truth:")
print (training_set_outputs)
print ("dot-product:")
print (np.dot(training_set_inputs, sweights) )
output = sigmoid(np.dot(training_set_inputs, sweights))
print ("output:")
print (output)
error = sigmoid(np.dot(training_set_inputs, sweights)) - training_set_outputs
print ("error:")
print (error)
print ("derivative:")
print (np.dot(training_set_inputs.T, error * sigmoid_derivative(output)) )

input:
[[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 0]]
truth:
[[0]
 [1]
 [1]
 [0]]
dot-product:
[[-0.99977125]
 [-0.72507825]
 [-1.16572724]
 [ 0.44064899]]
output:
[[ 0.2689864 ]
 [ 0.3262757 ]
 [ 0.23762817]
 [ 0.60841366]]
error:
[[ 0.2689864 ]
 [-0.6737243 ]
 [-0.76237183]
 [ 0.60841366]]
derivative:
[[-0.28621005]
 [-0.00314557]
 [-0.23331852]]
